name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Menggunakan Java 11, karena banyak project lama tidak support JDK 17
      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Paksa menggunakan Gradle 7.5 yang lebih cocok untuk project Android lama
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '7.5'

      - name: Buat Ulang File Gradle Wrapper
        run: gradle wrapper --gradle-version 7.5

      - name: Beri Izin Eksekusi Gradle
        run: chmod +x gradlew

      - name: Mulai Merakit APK (Build)
        run: ./gradlew assembleDebug

      - name: Upload Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Kasir-Offline
          path: app/build/outputs/apk/debug/app-debug.apk
